ViewBinding delegate
NUmeroAndDev/MaterialGallery-android pull request #439
Opened 2021-06-09 15:48 UTC by massivemadness

## Overview

ViewBinding delegate for binding fragment views automatically instead of manually doing `_binding = ViewBinding.bind(...)` and `_binding = null`. Also this allows to get rid of `onDestroyView` method

2021-06-23 07:19 UTC, NUmeroAndDev requested changes
Thank you for sending the pull request. 

This implementation is not good as the methods are not accessible when minify enabled.
How about using [this library](https://github.com/wada811/ViewBinding-ktx) instead?

2021-06-24 16:53 UTC, massivemadness commented
@NUmeroAndDev I prefer using my own implementation instead of many small libraries, I've changed it the way you wanted

2021-07-02 11:51 UTC, NUmeroAndDev commented
I don't like my own implementation.
Because I don't want to have the same implementation over and over in multiple projects.

2021-07-02 11:51 UTC, NUmeroAndDev approved these changes
LGTM 🙆‍♂️ 
Thanks contribute!!

2021-07-02 11:51 UTC, merged